onboarding = false
[keys]
prefix = "ctrl+;"
navigate_workspace_down = "j"
navigate_workspace_up = "k"

[experimental]
switch_ascii_input_source_in_prefix = true

[[keys.command]]
key = "ctrl+g"
type = "popup"
command = "lazygit"
description = "open Lazygit popup pain"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+shift+b"
type = "popup"
command = "~/dotfiles/scripts/herdr_worktree_from_remote_branch.sh"
description = "リモートブランチから worktree を作成"
width = "80%"
height = "80%"
